### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte

### ISSUE THREAD

**Issue by 1337heker** [hexedit/ext4extract#1]
Hello this tool has been working fine for a lot of raw EXT4 images (android)

But i encountered a issue in android 11 image

The issue looks like:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte`

I think its a external xattr issue or something and this tool doesn't process it and only does internal?

I can dump symlinks without a problem, but cant extract/dump metadata

I can attach a link to that image (2gb) if you are intersted to help me :)

Thank you!

**Comment by hexedit** [comment]
@yEsPaP Hello, I can try to find and fix it, and yes, please provide a link to image :)

**Comment by 1337heker** [comment]
okay. thank you for your response.

Heres the link: https://drive.google.com/uc?id=1LgZRBASX0LjBf-uJhXkQG8lSlbrWdGT7&export=download

If google drive is not fine for you i can mirror it elsewhere.

**Comment by 1337heker** [comment]
also worth noting: i can mount and fully extract the image under linux with this command: `sudo mount -t ext4 -o loop vendor.img vendor` so the image is not corrupted or something. Hope you can figure something out.

**Comment by hexedit** [comment]
It's interesting. There is incorrect inode location calculated and it's too strange. Or maybe group descriptor. Unfortunately, I need more time to properly debug this.

**Comment by hexedit** [comment]
It's strange why `bg_inode_table_*` points to 4th block even if block group doesn't contain superblock/GDT backup (in case of `sparse_super`)

**Comment by hexedit** [comment]
Please let me know if it fixes your issue :)

**Comment by 1337heker** [comment]
Yes thank you this works very well!
